name: s3-source-deploy
on:
  push:
    branches:
      - main

  release:
    types:
      - created

jobs:
  push-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ../ && ls -lah
      - uses: ./.github/actions/s3-deploy
        with:
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
